### ISSUE TITLE
GEt-jiraissue is slow

### ISSUE THREAD

**Issue by paul-sernine** [replicaJunction/PSJira#12]
Our JIRA has a lot of custom fields (800 for each ticket...) so it takes 10 seconds to retrieve one ticket.

I tracked down the issue, and the issue is in the function converting the result from the request to a jiraissue object. Please find enclosed a patch that accelerated greatly the speed of the function
[patch.diff.convertjiraissue.txt](https://github.com/replicaJunction/PSJira/files/51763/patch.diff.convertjiraissue.txt)

you may be able to reuse similar code at other places.

**Comment by replicaJunction** [comment]
Cool. Thanks for that code!  I don't have nearly that many custom fields in my instance, so performance had never been an issue.

I've implemented your changes in the latest commit to the dev branch.  Give that a try, and if it works as expected, I'll implement that change in several other places around the module.
