### ISSUE TITLE
Get-JiraGroupMember only returns the first 50 Users

### ISSUE THREAD

**Issue by Brightdawn** [replicaJunction/PSJira#14]
Get-JiraGroupMember only returns the first 50 Users of a group... any more members will be ignored...
can you implement getting all users of a group?

**Comment by replicaJunction** [comment]
Hi Brightdawn, this should be fixed in the latest build on the dev branch.  I'll be creating a new release in the next couple of days with the fix included.  Thanks for reporting this!
