### ISSUE TITLE
Set-JiraIssue cannot handle custom fields

### ISSUE THREAD

**Issue by Zer010** [replicaJunction/PSJira#2]
Is it possible to request this feature to specify a custom field like:

Set-JiraIssue -Key TEST-001 -Field "customfield_12345" -Value 2015-10-07T10:24:00.000-0700

or in a more RESTful manner have: 

Update-JiraIssue TEST-001

That way the changes done to TEST-001 get sync'd back.

Awesome job on this!

**Comment by replicaJunction** [comment]
Good call; Set-JiraIssue really should support custom fields.

I'm thinking a hashtable would make the most sense...similar to the Fields parameter in [New-JiraIssue](https://github.com/replicaJunction/PSJira/blob/master/PSJira%2FFunctions%2FNew-JiraIssue.ps1).  Something like this:

```powershell
Set-JiraIssue -Key TEST-001 -Fields @{
    'customfield_12345'=(Get-Date);
    'customfield_67890'='fred';
}

This would updating multiple fields at the same time.

**Comment by Zer010** [comment]
Awesome!! Looking forward to the next release. :)

/subscribed

**Comment by replicaJunction** [comment]
This has been added in release v1.1.1 (ec05d81)
