### ISSUE TITLE
Label support in New-JiraIssue prevents creation of issue

### ISSUE THREAD

**Issue by colhal** [replicaJunction/PSJira#21]
Since label support was added we can no longer create new Jira issues. New-JiraIssue.ps1 shows:
DEBUG: [Resolve-JiraError] Writing Error output for error [labels]
Resolve-JiraError : Jira encountered an error: [labels] - Field 'labels' cannot be set. It is not on the appropriate screen, or unknown.
Our workaround is to comment out creation of the $props.labels property in New-JiraIssues.ps1. Can a modification be made to exclude the creation of $props.labels if the $Labels parameter is blank or not passed? This will provide a more permanent solution. Thanks.

**Comment by colhal** [comment]
Another option would be to add a switch parameter to New-JiraIssues.ps1 (e.g. '-NoLabels') that would exclude labels from the $props definition. It would help us a lot if this minor change could be added. Thanks.

**Comment by replicaJunction** [comment]
Hi! Sorry about the delay on getting back to you here; I've had some life changes recently.

This looks like a pretty quick fix; it only happens when creating an issue without any labels, correct? If so, I'll try to get that taken care of in the next few days.

**Comment by colhal** [comment]
Hi Joshua, good to hear from you. Yes we only have difficulty creating new issues without labels. If you could make the minor change it would help us out. Thanks for your assistance.
Colin

**Comment by replicaJunction** [comment]
Go ahead and download the latest build from the dev branch. This issue should be fixed in the latest commit to that branch.

Assuming that's working correctly, I'll get a new release put together here and on the PowerShellGallery soon.

Thanks for the catch!
