### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by LiamLeane** [replicaJunction/PSJira#26]
When is the next release out to PSGallery to synchronize the JSON pull I made a little while back?

PS - Have you considered asking for an OSS license? https://www.atlassian.com/software/views/open-source-license-request

**Comment by replicaJunction** [comment]
A little late to the party...but it's been pushed to the gallery!

I've also changed up the release pipeline quite a bit, so stuff should get published to PSGallery any time it passes all Pester tests.
