### ISSUE TITLE
Unable to create sub-task issues because parent field is not accepted

### ISSUE THREAD

**Issue by ebekker** [replicaJunction/PSJira#29]
With the current cmdlet set, it's not possible to create an issue that is a sub-task because the issue requires a `Parent` to be specified, however the `New-JiraIssue` cmdlet does not accept a parent field because it is not returned in the set of available fields by the `Get-JiraField` cmdlet.

The missing `parent` field issue appears to be reflected by [this JIRA bug](https://jira.atlassian.com/browse/JRA-47377).  Presumably this is an *implied* global field.

But as shown in [this API tutorial](https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-create-issue#JIRARESTAPIExample-CreateIssue-Exampleofcreatingasub-task) example for creating sub-task issues, the parent is required.

**Comment by replicaJunction** [comment]
Cool, nice catch. I don't work with sub-tasks much, so I hadn't noticed the problem. Thanks for the fix - I'm merging it now.

**Comment by H-J-Simpson** [comment]
@ebekker is this issue solved? When I try to create a SubTask with New-JiraIssue 
I pass along this value:
parent       =   @{ key = $newParentIssue.Key}   
But all I am getting is an error saying "he issue no longer exists." 
I don't even know what that means :-)
Do you have any thoughts on that?

**Comment by lipkau** [comment]
@H-J-Simpson . This issue has been closed a long time ago.
Please create a new ticket including the code you are using as well as proof (`get-JiraIssue`) that the `$newParentIssue.Key` actually exists
