### ISSUE TITLE
How to track jira api version vs PSJira version?

### ISSUE THREAD

**Issue by alexsuslin** [replicaJunction/PSJira#33]

**Comment by replicaJunction** [comment]
Unfortunately, I don't think JIRA provides a method to do this. Their API versions don't match the product version of JIRA at all - as far as I know, they only have API versions 1, 2, and latest (a symlink to 2). They've been on version 2 for longer than I've been working on this project.

As far as I know, there isn't a REST function to get the version of JIRA you're querying.
