### ISSUE TITLE
UTF- 8 Encoding of Invoke-Webrequest Body

### ISSUE THREAD

**Issue by sipho102** [replicaJunction/PSJira#4]
Me again :)
You might want to add support for all the fun characters such as ä ü ö (wont even start with the nordic ones :))
Checkout: http://stackoverflow.com/questions/15290185/invoke-webrequest-issue-with-special-characters-in-json
You could pretty easily do that by encoding the body of the Webrequest in the Invoke-JiraMethod with something like:
$EncBody = [System.Text.Encoding]::UTF8.GetBytes($Body)
And then handing over the UTF8 body. Works very well for me.

PS: Sorry for not Push/Pulling such requests. Working on it with my IT security that our proxy allows it :-S

**Comment by replicaJunction** [comment]
Thanks for the info and the fix!. This should be resolved in the latest commit.
