### ISSUE TITLE
Add in -usebasicparsing to invoke-webrequests for use on Windows Server :) 

### ISSUE THREAD

**Issue by beaudryj** [replicaJunction/PSJira#41]
https://github.com/replicaJunction/PSJira/blob/master/PSJira/Internal/Invoke-JiraMethod.ps1

https://github.com/replicaJunction/PSJira/blob/master/PSJira/Public/New-JiraSession.ps1

**Comment by replicaJunction** [comment]
Should be fixed in that commit and published to the gallery!
