### ISSUE TITLE
Invoke-JiraMethod error when Invoke-WebRequest returns '204 No content'

### ISSUE THREAD

**Issue by colhal** [replicaJunction/PSJira#42]
When trying to use Set-JiraIssue the Jira issue updates as expected but I get the following error:
$objHash = @{
    customfield_11400 = @{
        id = "11317"
    }
}
Set-JiraIssue -Issue OPS-4526 -Credential $jiraCred -Fields $objHash

ERROR:
ConvertFrom-Json2 : Cannot bind argument to parameter 'InputObject' because it is an empty string.
At C:\Users\chalford\Documents\WindowsPowerShell\Modules\PSJira\1.2.5.112\Internal\Invoke-JiraMethod.ps1:93 char:54
$result = ConvertFrom-Json2 -InputObject $webResponse.Content

I traced the problem to Invoke-JiraMethod not being able to handle '204 No content' results from Invoke-WebRequest which according to the REST API documentation is the standard success response. Error trapping should test for  $webResponse.Content before calling ConvertFrom-Json2 or should have a test for ($webResponse.StatusCode -eq 204)

Hoping the above proves useful.
Regards.

**Comment by replicaJunction** [comment]
Thanks for catching this! Should be fixed with that commit.
