### ISSUE TITLE
Get-JiraIssue -Query 'project = "<projectName>"'  never returns a response

### ISSUE THREAD

**Issue by pdxpowershell** [replicaJunction/PSJira#47]
When running a Get-JiraIssue -Query 'project = "<projectName>"' never returns a valid response, and appears to be hung. The query had no response after 5 minutes of waiting, however, when performing the same JQL in Jira interface, the response is near immediate and populated.

**Comment by replicaJunction** [comment]
Hmm. What version of the module are you using? Latest at the moment is 1.2.5.133.

I receive an error message running that query, but it doesn't time out:
```
PS> Get-JiraIssue -Query 'project = ""' -Debug -Credential $c
Resolve-JiraError : Jira encountered an error: [The value '' does not exist for the field 'project'.]
At D:\Documents\Projects\PSJira\PSJira\Internal\Invoke-JiraMethod.ps1:111 char:13
+             Resolve-JiraError $result -WriteError
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError
```

That's definitely a JIRA error, not a PowerShell one (the module translates the body of the Web response into a native-looking PS error for convenience). It could just be the setup on my test instance; I don't have a blank project at the moment.

If you're on the latest version already, could you run Get-JiraIssue with the -Debug switch (or just set DebugPreference to "Continue") and post that output?
