### ISSUE TITLE
WARNING: JIRA returned HTTP error 

### ISSUE THREAD

**Issue by itokamak** [replicaJunction/PSJira#50]
You cannot call a method on a null-valued expression.

+             $readStream = New-Object -TypeName System.IO.StreamReader -ArgumentL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Pointing to New-JiraSession.ps1:92 char:13
$readStream = New-Object -TypeName System.IO.StreamReader -ArgumentList ($webResponse.GetResponseStream())

**Comment by replicaJunction** [comment]
Hi itokamak, thanks for the bug report.

Could I ask what version of PSJira you're using? At first glance, this looks like the same issue as #27 and #39 - in that case, all you'll need to do to fix this is update to the latest version of the module, then re-create your config file with `Set-JiraConfigServer`.

**Comment by itokamak** [comment]
Hi, thanks for the feedback, 
This is what we did initially, +deleted all configs, tried with earlier version too but still the same + happened to two users/machines.

**Comment by itokamak** [comment]
We set the wrong urls in Set-JiraConfigServer... 
Closing issue, sorry for opening it!

**Comment by replicaJunction** [comment]
Awesome. No problem at all - I'm glad you were able to get it sorted out!
