### ISSUE TITLE
Create Issue Without Priority

### ISSUE THREAD

**Issue by brianbunke** [replicaJunction/PSJira#52]
I have a project where the Priority field is hidden. I can't use New-JiraIssue to create an issue in this project, because the -Priority parameter is mandatory.

Confirmed with the following steps:

- Set a breakpoint on line 185 of New-JiraIssue
- Run New-JiraIssue with desired parameters
- Prompted to enter a value for mandatory parameter Priority
- Enter breakpoint
- `$json`
  - Includes the priority
- `$hashtable.fields.Remove('priority')`
- `$json = ConvertTo-Json -InputObject $hashtable -Depth 3`
- Exit breakpoint
- Issue is created successfully

Can you think of any reason this parameter needs to remain mandatory?

**Comment by replicaJunction** [comment]
Hmm, I've never run into a situation where priority isn't mandatory for actually creating an issue. If you run `Get-JiraIssueCreateMetadata` on that project, does Priority show that it's non-mandatory as well?

If it's not actually mandatory to JIRA, then there's no reason for the parameter to be mandatory, either.

**Comment by brianbunke** [comment]
Dictated by the applied field config scheme, issue type Task within project PROJ "hides" the Priority field in this instance. From memory, I'd guess Priority is required by default, but it's very easy to make it optional, and just as easy to hide if you're crazy like me.

Not that I've tested every scenario, but the assumption is that the required parameter easily applies to project & issue type combos where the field is both required and optional, and only chokes when the field isn't found.

``` powershell
PS> Get-JiraIssueCreateMetadata -Project PROJ -IssueType Task | Select Name,Required

Name          Required
----          --------
Assignee         False
Attachment       False
Epic Link        False
Description      False
Due Date         False
Linked Issues    False
Issue Type        True
Labels           False
Project           True
Reporter          True
Summary           True
```

**Comment by replicaJunction** [comment]
Fair enough. No reason to keep that parameter as mandatory, then.

I'll make the change as soon as I get a chance (or feel free to submit a PR for it).

**Comment by replicaJunction** [comment]
Merged and published to the Gallery. Thanks!
