### ISSUE TITLE
Add support for importing issues from CSV or other format

### ISSUE THREAD

**Issue by cloaked-ninja** [replicaJunction/PSJira#54]
It would be great to be able to import issues from other systems to JIRA using PSJira.  For example, CSV is probably one of the most commonly used files to do this.  Would save time to be able to import files from command line.

Documentation:
https://confluence.atlassian.com/adminjiraserver071/importing-data-from-csv-802592885.html

**Comment by replicaJunction** [comment]
Hey cloaked-ninja, you could use PowerShell's ```Import-Csv``` to do something like this:

```powershell
Import-Csv $env:USERPROFILE\Documents\jira-issues.csv | % {
    New-JiraIssue -Project $_.Project -IssueType $_.IssueType -Summary $_.Summary -Description $_.Description # etc.
}

Does that fit what you're looking for?

**Comment by cloaked-ninja** [comment]
I think so, thanks!
