### ISSUE TITLE
Trying to create New-JiraIssue with customfield

### ISSUE THREAD

**Issue by z0ph** [replicaJunction/PSJira#56]
Hello,

```
New-JiraIssue -Project SSC -IssueType Incident -Priority 1 -Reporter 'Lucie' -Summary 'Test issue from PowerShell' -Description 'This is a test issue created from the PSJira module in PowerShell.' -Fields @{
    'customfield_10482'='10413';
}
```

> WARNING: JIRA returned HTTP error 400 - BadRequest
Resolve-JiraError : Jira encountered an error: [customfield_10482] - Could not find valid 'id' or 'value' in the Parent 
Option object.

and without custom field : 

> WARNING: JIRA returned HTTP error 400 - BadRequest
Resolve-JiraError : Jira encountered an error: [Service_Support is required.]

Its a multi select item : When i run : 

`Get-JiraIssueCreateMetadata -Project SSC -IssueType Incident`

> Id              : customfield_10482
Name            : Service_Support
Schema          : @{type=option; custom=com.atlassian.jira.plugin.system.customfieldtypes:select; customId=10482}
HasDefaultValue : False
Required        : False
AllowedValues   : {@{self=http://jira:8080/rest/api/2/customFieldOption/10414; value=Cellule Metier; id=10414},
                  @{self=http://jira:8080/rest/api/2/customFieldOption/10610; value=Cellule BI; id=10610},
                  @{self=http://jira:8080/rest/api/2/customFieldOption/10413; value=Service Client; id=10413},
                  @{self=http://jira:8080/rest/api/2/customFieldOption/10415; value=Cellule Infrastructure; id=10415}}
Operations      : set

Could you help how to select this particular value with customfields.

Thanks for your help,

**Comment by replicaJunction** [comment]
Hey @z0ph, thanks for the great information on this issue!

Fields like this one with a list of allowed values need a slightly different syntax. I'm working off the top of my head (don't have access to my JIRA instance while I'm at work), but try this:

```powershell
$field = @{
    'customfield_10482' = @{
        id = 10413
        # You *might* also be able to do this with value = "Service Client" instead...not sure on that one
    }
}

New-JiraIssue -Project SSC -IssueType Incident -Priority 1 -Reporter 'Lucie' -Summary 'Test issue from PowerShell' -Description 'This is a test issue created from the PSJira module in PowerShell.' -Fields $field
```

Let me know how that goes!

**Comment by z0ph** [comment]
BOOM !

Thanks @replicaJunction its working with your code. Only added quotes :)

` id = '10413'`

**Comment by replicaJunction** [comment]
Awesome! Documentation is on my to-do list (#51) so I'll make a point of including this bit on custom fields as well.
