### ISSUE TITLE
Add-JiraIssueComment Cannot bind argument to parameter 'InputObject' because it is null

### ISSUE THREAD

**Issue by masyanru** [replicaJunction/PSJira#57]
1.2.5.135  PSJira
JIRA v7.1.7

Hello,
Everything works fine and I can get/create issues, but Add-JiraIssueComment doesn't create comments. 
I see that Jira returned 401, but get-jirasession shows me active session.  

> PS C:> Add-JiraIssueComment -Issue THD-3 -Comment "test"
> WARNING: JIRA returned HTTP error 401 - Unauthorized
> Exception calling "DeserializeObject" with "1" argument(s): "Invalid JSON primitive: ."
> At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.135\Internal\ConvertFrom-Json2.ps1:97 char:6
> -         $jsonTree = $jsonserial.DeserializeObject($InputObject)
> -         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>   - FullyQualifiedErrorId : ArgumentException
> 
> ConvertTo-JiraComment : Cannot bind argument to parameter 'InputObject' because it is null.
> At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.135\Public\Add-JiraIssueComment.ps1:113 char:54
> -         $result = ConvertTo-JiraComment -InputObject $rawResult
> -                                                      ~~~~~~~~~~
>   - CategoryInfo          : InvalidData: (:) [ConvertTo-JiraComment], ParameterBindingValidationException
>   - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,ConvertTo-JiraComment
> 
> PS C:> Get-JiraIssue THD-03 | Add-JiraIssueComment "Test comment from PowerShell (again)"
> WARNING: JIRA returned HTTP error 401 - Unauthorized
> The variable cannot be validated because the value  is not a valid value for the Body variable.
> At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.135\Internal\Invoke-JiraMethod.ps1:94 char:13
> -             $body = $readStream.ReadToEnd()
> -             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
>   - FullyQualifiedErrorId : ValidateSetFailure
> 
> ConvertFrom-Json2 : Cannot bind argument to parameter 'InputObject' because it is an empty string.
> At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.135\Internal\Invoke-JiraMethod.ps1:97 char:54
> -             $result = ConvertFrom-Json2 -InputObject $body
> -                                                      ~~~~~
>   - CategoryInfo          : InvalidData: (:) [ConvertFrom-Json2], ParameterBindingValidationException
>   - FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,ConvertFrom-Json2

**Comment by replicaJunction** [comment]
I'd start by investigating that 401 error. The other errors there are an issue with graceful error handling that I should take a look at, but they're not descriptive of the real problem.

Are you able to add a comment to that issue (THD-03) via the Web interface?

**Comment by masyanru** [comment]
![image](https://cloud.githubusercontent.com/assets/19715692/19601752/40d41c00-97b3-11e6-8ca1-49e322175a8b.png)

**Comment by replicaJunction** [comment]
Hmm, okay. I see you're not passing the -Credential param, so you're using a session, right?

Could you run the command in your first comment again with -Debug (or just change $DebugPreference to 'Continue') and post the debug output here? (Might need to sanitize URLs.)

**Comment by masyanru** [comment]
> so you're using a session, right?
yes, you can see get-jirasession below

PS C:\> Get-JiraSession
DEBUG: [Get-JiraSession] Module private data exists
DEBUG: [Get-JiraSession] A Session object is saved; outputting

Username   WebSession                                      JSessionID                       LoginInfo
--------   ----------                                      ----------                       ---------
%username% Microsoft.PowerShell.Commands.WebRequestSession 2D39FD612B63AB102620CC357BA42072 @{failedLoginCount=2; loginCount=363; lastFailedLoginTime=2016-03-24T14:21:06.215+0300; previousLoginTime=2016-10-31T12:24:42.278+0300}

and with $DebugPreference = "Continue"

PS C:\> Add-JiraIssueComment -Issue THD-3 -Comment "test"
DEBUG: [Add-JiraIssueComment] Begin
DEBUG: [Add-JiraIssueComment] Obtaining a reference to Jira issue [THD-3]
DEBUG: [Get-JiraIssue] Reading server from config file
DEBUG: [Get-JiraIssue] ParameterSetName=ByInputObject
DEBUG: [Get-JiraIssue] Processing InputObject [THD-3]
DEBUG: [Get-JiraIssue] Issue key is assumed to be [THD-3] via ToString()
DEBUG: [Get-JiraIssue] Invoking myself with the Key parameter set to search for issue [THD-3]
DEBUG: [Get-JiraIssue] Reading server from config file
DEBUG: [Get-JiraIssue] ParameterSetName=ByIssueKey
DEBUG: [Get-JiraIssue] Processing issue key [THD-3]
DEBUG: [Get-JiraIssue] Preparing for blastoff!
DEBUG: [Invoke-JiraMethod] Credentials were not provided. Checking for a saved session
DEBUG: [Get-JiraSession] Module private data exists
DEBUG: [Get-JiraSession] A Session object is saved; outputting
DEBUG: [Invoke-JiraMethod] A session was found; using saved session (Username=[%username%], JSessionID=[2D39FD612B63AB102620CC357BA42072])
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Get to URI https://jira.contoso.com/rest/api/latest/issue/THD-3?expand=transitions
DEBUG: [Invoke-JiraMethod] Status code: 200
DEBUG: [Invoke-JiraMethod] Converting body of response from JSON
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA
DEBUG: [Get-JiraIssue] Converting REST result to Jira object
DEBUG: [Get-JiraIssue] Outputting result
DEBUG: [Get-JiraIssue] Complete
DEBUG: [Get-JiraIssue] Returned from invoking myself; outputting results
DEBUG: [Get-JiraIssue] Complete
DEBUG: [Add-JiraIssueComment] Creating request body from comment
DEBUG: [Add-JiraIssueComment] Converting to JSON
DEBUG: [Add-JiraIssueComment] Preparing for blastoff!
DEBUG: [Invoke-JiraMethod] Credentials were not provided. Checking for a saved session
DEBUG: [Get-JiraSession] Module private data exists
DEBUG: [Get-JiraSession] A Session object is saved; outputting
DEBUG: [Invoke-JiraMethod] A session was found; using saved session (Username=[%username%], JSessionID=[2D39FD612B63AB102620CC357BA42072])
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Post to URI https://jira.contoso.com/rest/api/latest/issue/382469/comment
DEBUG: [Invoke-JiraMethod] Status code: BadRequest
WARNING: JIRA returned HTTP error 400 - BadRequest
The variable cannot be validated because the value  is not a valid value for the Body variable.
At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.135\Internal\Invoke-JiraMethod.ps1:94 char:13
+             $body = $readStream.ReadToEnd()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure

DEBUG: [Invoke-JiraMethod] Retrieved body of HTTP response for more information about the error ($body)
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA
DEBUG: [Add-JiraIssueComment] Converting to custom object
DEBUG: [Add-JiraIssueComment] Outputting result

DEBUG: [Add-JiraIssueComment] Complete
Body ID RestUrl Visibility
---- -- ------- ----------
test            @{value=Developers; type=role}

**Comment by replicaJunction** [comment]
Hmm...This run indicates an HTTP 400 error. Your initial run showed a 401 error...did anything change in your JIRA configuration?

I did make a small change that should resolve one of the errors you're experiencing here, but I don't know whether that will fix the underlying problem here or not. If you get a chance, go ahead and update to the latest module version (```Update-Module PSJira``` if you're on PS 5.0) and try again.

**Comment by masyanru** [comment]
I see, that the error was changed, but I didn't change Jira configuration.
This is strange. 
I updated to 1.2.5.136. "Get-JiraIssue THD-03" is still working normally.

PS C:\WINDOWS\system32> Get-Module -Name PSJira

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.2.5.136  PSJira                              {Add-JiraGroupMember, Add-JiraIssueComment, Format-Jira, Get-JiraConfigServer...}


PS C:\WINDOWS\system32> Add-JiraIssueComment -Issue THD-3 -Comment "test"
DEBUG: [Add-JiraIssueComment] Begin
DEBUG: [Add-JiraIssueComment] Obtaining a reference to Jira issue [THD-3]
DEBUG: [Get-JiraIssue] Reading server from config file
DEBUG: [Get-JiraIssue] ParameterSetName=ByInputObject
DEBUG: [Get-JiraIssue] Processing InputObject [THD-3]
DEBUG: [Get-JiraIssue] Issue key is assumed to be [THD-3] via ToString()
DEBUG: [Get-JiraIssue] Invoking myself with the Key parameter set to search for issue [THD-3]
DEBUG: [Get-JiraIssue] Reading server from config file
DEBUG: [Get-JiraIssue] ParameterSetName=ByIssueKey
DEBUG: [Get-JiraIssue] Processing issue key [THD-3]
DEBUG: [Get-JiraIssue] Preparing for blastoff!
DEBUG: [Invoke-JiraMethod] Credentials were not provided. Checking for a saved session
DEBUG: [Get-JiraSession] Module private data exists
DEBUG: [Get-JiraSession] A Session object is saved; outputting
DEBUG: [Invoke-JiraMethod] A session was found; using saved session (Username=[%username%], JSessionID=[BBDF85FF0A2A38A3AB1389EBD5111886])
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Get to URI https://jira.contoso.ru/rest/api/latest/issue/THD-3?expand=transitions
DEBUG: [Invoke-JiraMethod] Status code: 200
DEBUG: [Invoke-JiraMethod] Converting body of response from JSON
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA
DEBUG: [Get-JiraIssue] Converting REST result to Jira object
DEBUG: [Get-JiraIssue] Outputting result
DEBUG: [Get-JiraIssue] Complete
DEBUG: [Get-JiraIssue] Returned from invoking myself; outputting results
DEBUG: [Get-JiraIssue] Complete
DEBUG: [Add-JiraIssueComment] Creating request body from comment
DEBUG: [Add-JiraIssueComment] Converting to JSON
DEBUG: [Add-JiraIssueComment] Preparing for blastoff!
DEBUG: [Invoke-JiraMethod] Credentials were not provided. Checking for a saved session
DEBUG: [Get-JiraSession] Module private data exists
DEBUG: [Get-JiraSession] A Session object is saved; outputting
DEBUG: [Invoke-JiraMethod] A session was found; using saved session (Username=[%username%], JSessionID=[BBDF85FF0A2A38A3AB1389EBD5111886])
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Post to URI https://jira.contoso.ru/rest/api/latest/issue/382469/comment
DEBUG: [Invoke-JiraMethod] Status code: BadRequest
WARNING: JIRA returned HTTP error 400 - BadRequest
DEBUG: [Invoke-JiraMethod] Retrieved body of HTTP response for more information about the error ($responseBody)
ConvertFrom-Json2 : Cannot bind argument to parameter 'InputObject' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.136\Internal\Invoke-JiraMethod.ps1:97 char:54
+             $result = ConvertFrom-Json2 -InputObject $responseBody
+                                                      ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json2], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,ConvertFrom-Json2

DEBUG: [Invoke-JiraMethod] Outputting results from JIRA
DEBUG: [Add-JiraIssueComment] Converting to custom object
ConvertTo-JiraComment : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.136\Public\Add-JiraIssueComment.ps1:113 char:54
+         $result = ConvertTo-JiraComment -InputObject $rawResult
+                                                      ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertTo-JiraComment], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,ConvertTo-JiraComment

DEBUG: [Add-JiraIssueComment] Outputting result
DEBUG: [Add-JiraIssueComment] Complete

**Comment by vjangrus** [comment]
We are also having this issue. 
WARNING: JIRA returned HTTP error 400 - BadRequest
ConvertFrom-Json2 : Cannot bind argument to parameter 'InputObject' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.136\Internal\Invoke-JiraMethod.ps1:97 char:54
+             $result = ConvertFrom-Json2 -InputObject $responseBody
+                                                      ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json2], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,ConvertFrom-Json2

**Comment by masyanru** [comment]
@vjangrus try doing this
Add-JiraIssueComment -Comment "test" -Issue "THD-3" **-VisibleRole 'All Users'**
I think it depends on your Jira's security settings.
Now It works fine. ;)) 

Visibility   :
ID           : 1057217
UpdateAuthor : %username%
Author       : %username%
Created      : 15.11.2016 17:14:50
Updated      : 15.11.2016 17:14:50
Body         : test
RestUrl      : https://jira.contoso.com/rest/api/2/issue/382469/comment/1057217
