### ISSUE TITLE
Security Level for comments or Issue

### ISSUE THREAD

**Issue by z0ph** [replicaJunction/PSJira#58]
Hello,

Could you please tell me how to setup security level field on comments or issue ?

I think i should use : 

```powerhsell
#@{'Security Level'= '10401'}
```

But how do you find this id of the security level, i can't find out on Jira documentation.

I need to post comment and issue visible to "everyone"

Actually, my comments are limited to "Developpers"

Thanks for your help,
zoph

**Comment by z0ph** [comment]
Got my answer.

I need to use : 

```powershell
-VisibleRole All Users
```

**Comment by replicaJunction** [comment]
That's the one! :grin:
