### ISSUE TITLE
Help With Custom Fields

### ISSUE THREAD

**Issue by mcornille** [replicaJunction/PSJira#61]
Hi,

First of all nice work, this module saves me time.
But i have a question about Set-JiraIssue
I want to update a custom field but this custom field is a dropdown field how do i update this?

field is called "Environment Sx" (customfield_11154)
Possible values: Production, Test, Acceptance, Development
I tried the following commands but that did not work:
Current value of that field is Development or id 14753 and i want to update it to production or id 14750

`Set-JiraIssue -Issue $JiraIssue -Fields @{'Environment Sx' = 'Production';}`

`Set-JiraIssue -Issue $JiraIssue -Fields @{'Customfield_11154' = 'Production';}`

`Set-JiraIssue -Issue $JiraIssue -Fields @{'Customfield_11154' = '14750';}`
14750 = Value Production

But the result of all the commands are the same: **WARNING: JIRA returned HTTP error 400 - BadRequest**
![result](https://cloud.githubusercontent.com/assets/23481633/20617002/6c5e9000-b2e6-11e6-9842-7694066513dd.png)

It is possible to get the current value:
$JiraIssue.customfield_11154
returns:
![return](https://cloud.githubusercontent.com/assets/23481633/20617001/6c5d146e-b2e6-11e6-81cd-a71800eaf548.png)

Is custom field with dropdown not supported or is my code wrong?

**Comment by replicaJunction** [comment]
Take a look at #56 - there's some syntax quirks when your field only allows specific values.

Basically, you'll want something like this:

```powershell
$field = @{
    'customfield_11154' = @{
        id = '14750' # Production
        # You *might* also be able to do this with value = "Production" instead...not sure on that one
    }
}

Set-JiraIssue -Issue $JiraIssue -Fields $field
```

**Comment by lipkau** [comment]
I created the PR https://github.com/replicaJunction/PSJira/pull/59 exactly for that reason.
I created the Get-JiraissueEditMetadata function, so I can query the allowed values of a field. Then you can get the id of the element with the value you are looking for

**Comment by hvikesaa** [comment]
What about a customfield with labels?
Get-JiraField gives this:

> ID          : customfield_14560
> Searchable  : True
> Schema      : @{type=array; items=string; custom=com.atlassian.jira.plugin.system.customfieldtypes:labels; customId=14560}
> Name        : Model ID
> Custom      : True
> Navigable   : True
> Orderable   : True
> ClauseNames : {cf[14560], Model ID}
> 

What I have tried is this:
`$field = @{
    'customfield_14560' = @(@{
       'customfield_14560' = 'PROD'
        })
    }`

Error is:

> Resolve-JiraError : Jira encountered an error: [customfield_14560] - string expected at index 0
> At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.136\Internal\Invoke-JiraMethod.ps1:111 char:13
> +             Resolve-JiraError $result -WriteError
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError

**Comment by lipkau** [comment]
Based on the error description, I would try:
$field = @{ 'customfield_14560' = @('PROD') }

**Comment by hvikesaa** [comment]
That worked, thanks!

**Comment by hvikesaa** [comment]
Since this worked out so well, I have another one.

From Get-JiraIssueCreateMetadata:

> Id              : customfield_14662
> Name            : Server OS
> Schema          : @{type=option-with-child; custom=com.atlassian.jira.plugin.system.customfieldtypes:cascadingselect; customId=14662}
> HasDefaultValue : False
> Required        : False
> AllowedValues   : {@{self=https://jira.internal.com/rest/api/2/customFieldOption/20140; value=Windows; id=20140; children=System.Object[]}, @{self=https://jira.internal.com/rest/api/2/customFieldOption/20141; value=Linux; id=20141; children=System.Object[]}, @{self=https://jira.internal.com/rest/api/2/customFieldOption/20143; value=Other; id=20143; children=System.Object[]}}
> Operations      : set

```
$field = @{
    'customfield_14662' = @{
        id = '20140'
    }
}
```
It's no problem setting just the main field, but how to get the allowed values for the child-field, and how to set them?
I can of course see the allowed values in Jira (for Linux the field populates with ie. RHEL, CentOS etc, for Windows it's 2008, 2012...)

**Comment by lipkau** [comment]
What is the metadata for the child fields?

**Comment by hvikesaa** [comment]
Where can I find it? It's not a separate custom field.
An Issue that on the web shows both as "**Server OS:    Windows - 2012 R2**" and "**Server OS:    Windows - 2008 R2**", shows like this with Get-JiraIssue:

customfield_14662
-----------------
@{self=https://jira.internal.com/rest/api/2/customFieldOption/20140; value=Windows; id=20140; child=}

**Comment by hvikesaa** [comment]
Using the REST API, I got the following output from that same issue:
![image](https://cloud.githubusercontent.com/assets/24569022/21561816/33b7d084-ce72-11e6-9440-3979dd501911.png)
And with PSjira:
![image](https://cloud.githubusercontent.com/assets/24569022/21561821/3ed59b54-ce72-11e6-94b3-c8819aac7b15.png)

**Comment by replicaJunction** [comment]
Give this a try. I'm guessing a little bit here, but I _think_ this will work:

```powershell
$field = @{
    'customfield_14662' = @{
        id = '20140'
        child = @{
            value = '2008 R2
        }
    }
}

# Add other params like reporter, priority, etc.
New-JiraIssue -Fields $field
```

**Comment by hvikesaa** [comment]
Works perfect! Thanks!
