### ISSUE TITLE
-Repoter is mandatory in New-JiraIssue

### ISSUE THREAD

**Issue by lipkau** [replicaJunction/PSJira#64]
### Problem
It is not possible to create an Issue without providing a _reporter_.

This can lead to the following error (as it does for me):
> WARNING: JIRA returned HTTP error 400 - BadRequest
> Resolve-JiraError : Jira encountered an error: [reporter] - Field 'reporter' cannot be set. It is
> not on the appropriate screen, or unknown.

### Reason
When no value is provided to the parameter `Reporter`, as it is not mandatory in the `param()` section of `New-JiraIssue`, the function sets a "fallback" value:
```
        if ($Reporter)
        {
        } else {
            $reporterStr = $env:USERNAME
        }

        $ReporterParam = New-Object -TypeName PSObject -Property @{"name"=$reporterObj.Name}

        $props = @{
            "reporter"=$ReporterParam
        }
```

### Possible Solution
```
    {
        $ProjectParam = New-Object -TypeName PSObject -Property @{"id"=$ProjectObj.Id}
        $IssueTypeParam = New-Object -TypeName PSObject -Property @{"id"=[String] $IssueTypeObj.Id}

        $props = @{
            "project"=$ProjectParam;
            "summary"=$Summary;
            "issuetype"=$IssueTypeParam;
        }
        if ($Priority) {
            $props.priority = New-Object -TypeName PSObject -Property @{"id"=[String] $Priority}
        }

        if ($Description) {
            $props.description = $Description
        }

        if ($Reporter) {
            $props.reporter = New-Object -TypeName PSObject -Property @{"name"=$reporterObj.Name}
        }
```

**Comment by replicaJunction** [comment]
Interesting. I've never run into a situation where I didn't need to specify the reporter when creating a JIRA issue. Since that's possible, though, this change makes sense. If a reporter is required and not specified, JIRA will react the same way it would if any other mandatory field wasn't provided.

**Comment by KurtDeGreeff** [comment]
I also have the same issue over here, even with or without supplying credential or reporter parameter

New-JiraIssue -Project PST -IssueType Task -Priority 3  -Summary 'Modify PST' -Description 'test' -Credential $cred2 -Reporter 'u508416'
WARNING: JIRA returned HTTP error 400 - BadRequest
Resolve-JiraError : Jira encountered an error: [reporter] - Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown.
At C:\Users\u508416\Documents\WindowsPowerShell\Modules\PSJira\1.2.5.145\Internal\Invoke-JiraMethod.ps1:111 char:13
+             Resolve-JiraError $result -WriteError
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError
 

PS C:\Users\u508416> New-JiraIssue -Project PST -IssueType Task -Priority 3  -Summary 'Modify PST' -Description 'test' -Reporter 'u508416'
WARNING: JIRA returned HTTP error 400 - BadRequest
Resolve-JiraError : Jira encountered an error: [reporter] - Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown.
At C:\Users\u508416\Documents\WindowsPowerShell\Modules\PSJira\1.2.5.145\Internal\Invoke-JiraMethod.ps1:111 char:13
+             Resolve-JiraError $result -WriteError
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError
 

PS C:\Users\u508416> New-JiraIssue -Project PST -IssueType Task -Priority 3  -Summary 'Modify PST' -Description 'test'
WARNING: JIRA returned HTTP error 400 - BadRequest
Resolve-JiraError : Jira encountered an error: [reporter] - Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown.
At C:\Users\u508416\Documents\WindowsPowerShell\Modules\PSJira\1.2.5.145\Internal\Invoke-JiraMethod.ps1:111 char:13
+             Resolve-JiraError $result -WriteError
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Resolve-JiraError

**Comment by replicaJunction** [comment]
Resolved and published to the Gallery. I've removed the fallback logic for Reporter.
