### ISSUE TITLE
Testing of TypeName

### ISSUE THREAD

**Issue by JohnLBevan** [replicaJunction/PSJira#79]
The same code is used across multiple tests to check the type names of various objects.
Would be good to refactor this to a common function to make maintenance of this check simpler. 
Also good to agree a consistent approach to checking; see below for some examples with comments.

```
function Assert-HasTypeName {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [string]$TypeName
        ,
        [Parameter(Mandatory, ValueFromPipeline)]
        [PSObject]$InputObject
    )
    process {
        #$InputObject.PSObject.TypeNames[0] | Select-Object -Unique | Should Be $TypeName     #NB: Works but only if the typename is the first in the list
        #$InputObject.PSObject.TypeNames  | Should Contain $TypeName                          #NB: Pester uses CONTAIN for files; not arrays.
        #$TypeName | Should BeIn $InputObject.PSObject.TypeNames                              #NB: This works, but is Yodad (i.e. expected and actual are switched)
        #$InputObject.PSObject.TypeNames | ?{$_ -eq $TypeName} | Should Be $TypeName          #NB: Works but the "but was" value is blank, rather than a list of the property's typenames
        #$InputObject.PSObject.TypeNames.Contains($TypeName) | Should Be $True                #NB: Works but the expected and actual values listed as true/false instead of actual typenames 
        #$InputObject.PSObject.TypeNames -Contains $TypeName | Should Be $True                #NB: same as previous
        ($InputObject | Get-Member).TypeName | Select-Object -Unique | Should Be $TypeName    #NB: Works but only if the typename is the first in the list
    }
}

[string]$DemoTypeName = 'Demo'
[PSObject]$x = new-object -TypeName PSObject -Property @{hello="world"}
#$x.PSObject.TypeNames.Add($DemoTypeName) #NB: this would fail most tests as the target typename is not the first typename listed
$x.PSObject.TypeNames.Insert(0, $DemoTypeName)
$x | Assert-HasTypeName $DemoTypeName
```

NB: There is an open request for this feature in Pester which would simplify our choices here: https://github.com/pester/Pester/issues/121
If refactored at least we can easily implement the preferred logic once it's available.

**Comment by lipkau** [comment]
I disagree with this approach.
Public functions also check if the input parameter is of a certain type. Ex:
`if ((Get-Member -InputObject $i).TypeName -eq 'PSJira.User')`

therefor, I would plead to:
* either have two functions (one for pester and one as internal function for public ones)
* or have this function only return `bool` and the functions that called it evaluates the output however it pleases

**Comment by JohnLBevan** [comment]
Ah ok; so rather than refactor the test logic into its own function, refactor the HasType logic so it can be used in both tests and in the actual functionality:

In Tests:
`$r | Test-HasTypeName 'PSJira.User' | Should Be $True` 

In Functionality:
```
if ($Issue | Test-HasTypeName 'PSJira.Issue')
{
	Write-Debug "[Add-JiraIssueComment] Issue parameter is a PSJira.Issue object"
	$issueObj = $Issue
} else {
	#...
}
```

**Comment by lipkau** [comment]
+1

**Comment by JohnLBevan** [comment]
Refactored code committed.
