### ISSUE TITLE
get-JiraIssue does not use StartAt

### ISSUE THREAD

**Issue by paul-sernine** [replicaJunction/PSJira#9]
Hi,

any chance to add the StartAt when requesting the search endpoint ? it would allow to get all issue.

Even better, maybe all to retrieve all items by looping ?

**Comment by paul-sernine** [comment]
[patch.diff.txt](https://github.com/replicaJunction/PSJira/files/48130/patch.diff.txt)

here is a patch to do the first part

**Comment by replicaJunction** [comment]
Good idea.  I've implemented both the StartAt and the looping behavior.  By default, Get-JiraIssue will now loop and retrieve all issues when searching by a filter or JQL query; you can override this by specifying the MaxResults parameter.

This has been implemented in the latest commit to Dev.  I'll make a new release and push this to the PowerShell Gallery later today to address this and #7.
